### PR TITLE
Add Site Config for ROSCon 2022

### PR DESCRIPTION
**Pull request by cmelliott2**
Added a site config for ROSCon 2022

### CODE REVIEW

**Review by corycrean — CHANGES_REQUESTED** [review]
Can we generate read-only SSH keys for this repo?

**Comment by cmelliott2** [comment]
> Can we generate read-only SSH keys for this repo?

@nbbrooks Can you create this and add it to the GDrive folder with the ones for Studio and the kinova driver? I think you own the other two

**Comment by nbbrooks** [comment]
@cmelliott2 do I still need to do that since the repo is now public?

**Comment by cmelliott2** [comment]
> @cmelliott2 do I still need to do that since the repo is now public?

@nbbrooks  Nope! Thanks

**Comment by cmelliott2** [comment]
@corycrean After testing this LGTM. I cannot approve as the author though. I say we merge and then we can make tweaks as necessary

**Comment by cmelliott2** [comment]
Small nit, we should make the scene camera invisible. But I see that on Charmander too so the fix is either in the base config or at least needs to be made in all UR5e configs

**Review by corycrean — APPROVED** [review]

**Pull request merged**
